### PR TITLE
Sync history conversation of the Chat

### LINKED ISSUE #2937: Click here to get older messages from your phone
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

image

If from web WhatsApp, user can click the button on top of the chat and start loading the older messages from phone until like 3 months ago.

Do we have the option in this library to load older messages?

There is a similar issue which mark as completed https://github.com/pedroslopez/whatsapp-web.js/issues/2478
[Chat.fetchMessages](https://docs.wwebjs.dev/Chat.html#fetchMessages) Is not working at all even I set limit to 999, the chat is only 10 messages only and I can't do anything on it.

### Expected behavior

Able to load the messages by clicking the button

### Steps to Reproduce the Bug or Issue

1. Open a chat
2. Scroll up
3. Click older message 

### Relevant Code

waClient.getChatById(req.query.from)
		.then(async function (chat) {
			await chat.fetchMessages({
				limit: 999,
			})
				.then(async function (allMsg) {
					console.log(allMsg.length); // I only get 10 messages and there are a lot more message which is only 1 week ago is not showing
                               });
                  });

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Windows
Phone OS: Android
whatsapp-web.js version 1.23.1-alpha.3
WhatsApp Web version [run await client.getWWebVersion()]:
Node.js Version 20.11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by momokang**
# PR Details

Sync history conversation of the Chat

## Description

Able to sync historical message of the Chat

## Related Issue

closes #2937

## Motivation and Context

After historical messages are synced, you can fetch older messages content, images, attachment and audio.

## How Has This Been Tested

User can type !syncHistory to sync the historical message, alternatively, can change the chatId in await client.syncHistory(chatId); to test out

## Types of changes

- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).

### CODE REVIEW

**Review by alechkos — CHANGES_REQUESTED** [review]
@momokang Good job!
I haven't done the testing yet, but it looks working.
Please go through the comments

File: src/Client.js [hunk 1]
```diff
@@ -1739,6 +1739,24 @@ class Client extends EventEmitter {
...
         return 0;
     }
+
+    /**
+     * Sync history conversation
+     * @param {string} chatId
+     * @return {boolean} true/false
+     */
+    async syncHistory(chatId) {
+        return await this.pupPage.evaluate(async (chatId) => {
```
Comment (alechkos) [inline src/Client.js:1749]: We don't need to use `await` here since the method already returns `Promise`.
```suggestion
        return this.pupPage.evaluate(async (chatId) => {
```

**Review by alechkos — COMMENTED** [review]
@momokang Tested and works perfect!
Please fix issues and I'll approve it.

**Comment by momokang** [comment]
@alechkos Thanks for the review, it's amended accordingly

**Review by alechkos — APPROVED** [review]
Good work!

File: src/Client.js [hunk 2]
```diff
@@ -1739,6 +1739,24 @@ class Client extends EventEmitter {
...
         return 0;
     }
+
+    /**
+     * Sync chat history conversation
+     * @param {string} chatId
+     * @return {Promise<boolean>} True if operation completed successfully, false otherwise.
+     */
+    async syncHistory(chatId) {
+        return this.pupPage.evaluate(async (chatId) => {
```
Comment (shirser121) [inline src/Client.js:1749]: Why there is not await?

Comment (alechkos) [reply src/Client.js:1749]: @shirser121 
`async syncHistory(chatId)`, this aready returns `Promise`, you then call it like that:
```js
await syncHistory(...)
```

**Review by shirser121 — APPROVED** [review]
Thanks

**Comment by shawngoh87** [comment]
I've tried using this on a fresh linked device and new puppeteer instance (no cache), the method kept returning `false` but `fetchMessages` actually returns all the messages.

**Comment by Furqanameen** [comment]
That feature worked well.
but don't know why it has not been loading and working for all chats.
even If go back to some numbers whose contacts I made months ago, it's not loading the entire history, even though on mobile it's available and can be accessed
